"""initial migration

Revision ID: 315270de0566
Revises: 
Create Date: 2018-03-22 16:27:36.683138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315270de0566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PersonalGifCollection', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'PersonalGifCollection', 'users', ['user_id'], ['id'])
    op.add_column('gifs', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.add_column('gifs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gifs', 'PersonalGifCollection', ['collection_id'], ['id'])
    op.create_foreign_key(None, 'gifs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gifs', type_='foreignkey')
    op.drop_constraint(None, 'gifs', type_='foreignkey')
    op.drop_column('gifs', 'user_id')
    op.drop_column('gifs', 'collection_id')
    op.drop_constraint(None, 'PersonalGifCollection', type_='foreignkey')
    op.drop_column('PersonalGifCollection', 'user_id')
    # ### end Alembic commands ###
